command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: CDP_AGENT_ENDPOINT
    valueFrom: serving-endpoint

  - name: CDP_CATALOG
    value: "ahs_demos_catalog"

  - name: CDP_SCHEMA
    value: "cdp_360"

  - name: CDP_DATA_SOURCE
    value: "databricks"

  - name: CDP_GENIE_SPACE_ID
    valueFrom: genie-space
